### ISSUE TITLE
Thermometer journey_patern order inconsistence 

### ISSUE THREAD

**Issue by xavierraffin** [hove-io/navitia#1159]
In thermometer of the following 

```
{1,2},{3,2},{0,1,2},{0,3,2}
```

is

```
{0,1,3,2}
```

But thermometer of  (two last are inverted)

```
  {1,2},{3,2},{0,3,2},{0,1,2}
```

is

```
{1,0,1,3,2}
```

The last one cause bad things in route_schedules (same stop displayed twice)

The thermometer algorithm looks touchy, so I would like to agree with you that this behaviour is wrong before doing something.

My proof, these tests pass :

```

BOOST_AUTO_TEST_CASE(t16) {
    Thermometer t;
    std::vector<vector_idx> req;
    req.push_back({1,2});
    req.push_back({3,2});
    req.push_back({0,3,2});
    req.push_back({0,1,2});

    t.generate_thermometer(req);
    auto result = t.get_thermometer();

    BOOST_REQUIRE_EQUAL(result[0], 1);
    BOOST_REQUIRE_EQUAL(result[1], 0);
    BOOST_REQUIRE_EQUAL(result[2], 1);
    BOOST_REQUIRE_EQUAL(result[3], 3);
    BOOST_REQUIRE_EQUAL(result[4], 2);
}

BOOST_AUTO_TEST_CASE(t17) {
    Thermometer t;
    std::vector<vector_idx> req;
    req.push_back({1,2});
    req.push_back({3,2});
    req.push_back({0,1,2});
    req.push_back({0,3,2});

    t.generate_thermometer(req);
    auto result = t.get_thermometer();

    BOOST_REQUIRE_EQUAL(result[0], 0);
    BOOST_REQUIRE_EQUAL(result[1], 1);
    BOOST_REQUIRE_EQUAL(result[2], 3);
    BOOST_REQUIRE_EQUAL(result[3], 2);
}

```

**Comment by TeXitoi** [comment]
`{0,1,3,2}` is better than `{1,0,1,3,2}`, but the two are valid solutions. The problem is NP-Complete, thus or we use an exact exponential algorithm, or a polynomial heuristic (or P = NP). See http://labs.canaltp.fr/2012/12/fiche-horaire-et-np-completude/ for more information.

Now, we use an heuristic, but it's not great. If you have a proposition to make a better heuristic (or an exact algorithm that is usable in practice), we are listening to you (I didn't have the time to look at it yet).

**Comment by xavierraffin** [comment]
So you agree that the behaviour is not optimal and **could** be improved.

Fine.

But that behaviour cause a bug in route_schedules so it **must** be fixed.

## Bug description

In route_schedules (heavily used by TimeTable) the stop times are showed for each stop of the thermometer.
Sometimes (when a line loops) there is some stops showed several time in the timetable.
But because of inconsistent behaviour of thermometer, depending on random things like trip ordering in ntfs a stop could be showed twice.
Think about Timetable (the software) situation :

From TimeTable point of view, there is no differences beetween a legitimateand an illegitimate doubled stops.

Because thermometer hide information about trips, this is to late to recover.

## Coding considerations

The thermometer algorithm is touchy and It will take time for me to fix it.

Additionnaly the algorithm is iterative, so it inherently is order sensitive.
If I fix it I need to change it deeply, which can cause a lot of side effects for your use cases.

So are you OK to fix it yourself (I know this is a  hard work) ?

**Comment by TeXitoi** [comment]
Here is some point I would like to clarify.

If the route schedule is valid, we generally do not consider it as a blocking bug. For us, the route schedule is valid if it is such as:
- no stop times are lost;
- the stop times are in order.

So, if a stop_point appears many times, it may not be considered as a bug, but as a sub-optimal solution.
In fact, I am not sure I understand correctly your case. Maybe an example can help. 

Here is some action we may look at together:
1. If you have an algorithm that is correct and gives better solution than the current implementation, you can propose a complete rewrite of thermometer.{h,cpp}. No need to understand the current algorithm. We'll be happy to review it :)
2. We can imagine that, in the ntfs, a thermometer can be provided to a route. Then, if the thermometer is valid, the code will use it instead of computing it > easy and without surprise :)

We are currently very buzzy on other subjects, we won't be able to work on this problem (if the route schedule is valid) at least until November.

Maybe we can talk about that when you'll come in Paris to meet us?

**Comment by xavierraffin** [comment]
OK We have to talk in Paris.

I let the issue open until we decide what to do.

Thank you

**Comment by TeXitoi** [comment]
OK, I've found an algorithm that should be quite easy to implement, and will always be better that the current algorithm. If there is a solution where no stop point are repeated, the algorithm will find it. Else, the algorithm fail, and we launch the old one.
1. Create a [graph](http://www.boost.org/doc/libs/1_59_0/libs/graph/doc/table_of_contents.html) with a node for each stop point. For each successive stop points in a JP, create an arc between the 2 corresponding nodes.
2. Do a [topological sort](http://www.boost.org/doc/libs/1_59_0/libs/graph/doc/topological_sort.html) on this graph.
   - If the graph contains a cycle, the topological sort fails, and there is no feasible solution to the thermometer without duplicating at least one stop point. In this case, we launch the current algorithm.
   - Else, the order of the topological sort is a correct order without duplication of stop point. Return it.

For your example `{1,2},{3,2},{0,3,2},{0,1,2}`, you'll generate this graph:

```
0 --> 3
|     |
V     V
1 --> 2
```

And the topological sort gives `0 -> 1 -> 3 -> 2` (or `0 -> 3 -> 1 -> 2`) as wanted.

If you want, you can code that, and I'll be happy to review it. Else, I'll do that when I'll have the time.

**Comment by xavierraffin** [comment]
Great.
I don't know if I will have enough spare time to do it soon.

I will tell you in Paris the 17th.

Keep in touch ;-)

2015-09-04 17:28 GMT+02:00 Guillaume P. notifications@github.com:

**Comment by xavierraffin** [comment]
I start working on it.

I will try your boost proposition first.
