### ISSUE TITLE
[jormungandr] cannot import name response_pb2

### ISSUE THREAD

**Issue by beeksiwaais** [hove-io/navitia#1575]
When I run manage.py in jormungandr :
`from navitiacommon import response_pb2, type_pb2
ImportError: cannot import name response_pb2`

I understand that is probably related to protobuf but I am not an expert in Python.

Any idea ?

**Comment by beeksiwaais** [comment]
I try to extract jormungandr so I don't compile navitia.

**Comment by antoine-de** [comment]
those are generated files (protobuf generate those files during the compilation)

how did you install navitia ? did you use the debian packages ? the protobuf files should be in the packages.

If you install navitia manually, you need to generate those files, either by compiling (they will be generated in navitiacommon/navitiacommon/) or by calling manually the `protoc` executable to generate them ( something line `protoc --python_out=/home/antoine/dev/navitia/source//navitiacommon/navitiacommon type.proto response.proto request.proto task.proto stat.proto`

**Comment by beeksiwaais** [comment]
Hi, 

I try to decompose different part of navitia to put them in docker containers. Containers should be as small as possible in order to use them as microservices.
I also took some notes of what currently does not allow a true microservices approach (for example authentication).

I will try your command.

**Comment by antoine-de** [comment]
Hi, yes It would be great!

we have several docker approaches but indeed way too monolithic :confused: 

I'm really interested in you work and i'm open to discuss it with you (why does the microservices approach is broken by authentication ?).

in addition to the docker hub image you can have a look at: https://github.com/CanalTP/navitia_image_manager/tree/master/docker_compose/artemis

that split the navitia images 'a bit' (but the approach is broken because the Dockerfile are not sufficient, it relies on our fabric deployement scripts)

**Comment by beeksiwaais** [comment]
The command wrought but I have been able to generate a self contained jormungandr (but not optimize at all).

I will push a working navitia composed of microservices soon. I will try to document everything. Be patient ,-)
