### ISSUE TITLE
Pagination for departures at stop_area

### ISSUE THREAD

**Issue by tufftuff93** [hove-io/navitia#2698]
Pagination for departures at stop_area doesn't show the total_result for the duration.

When I ask for the next departures for a specific day (24H)
https://api.navitia.io/v1/coverage/fr-idf/stop_areas/stop_area%3AOIF%3ASA%3A59%3A5355357/departures?from_datetime=20190312T120000&duration=86400

![image](https://user-images.githubusercontent.com/26787507/53864134-029a2900-3fec-11e9-8d59-9be3a927eeee.png)

I get the 10 next departures, but pagination object show a total result of 10 objects. 

There is more than 10 departures this day:
https://api.navitia.io/v1/coverage/fr-idf/stop_areas/stop_area%3AOIF%3ASA%3A59%3A5355357/departures?from_datetime=20190312T120000&duration=86400&count=30

![image](https://user-images.githubusercontent.com/26787507/53864251-4f7dff80-3fec-11e9-9e5a-437f084e4f5e.png)

So I try to browse the page 1 using the same urls
https://api.navitia.io/v1/coverage/fr-idf/stop_areas/stop_area%3AOIF%3ASA%3A59%3A5355357/departures?from_datetime=20190312T120000&duration=86400&count=30&start_page=1

![image](https://user-images.githubusercontent.com/26787507/53864379-9d930300-3fec-11e9-87f5-45ca0bd0d77e.png)

The departures list is empty and pagination show 0 items_on_page. 

I have this behavior with navitia.io and with a local instance of navitia.

**Comment by ArthurLeyv** [comment]
Hi, thanks for reporting this  issue !

**Comment by ArthurLeyv** [comment]
Hi tufftuff93 ! 

Thanks for reporting this issue. 

What’s your need in this case?

There are 3 ways to address this: 
-	The first one is to use “/departure” which is set by default on “data_freshness=realtime” to have the X next departures at the stop_area. There is no pagination for this, data is moving constantly and it would be difficult to keep the next page with the right data. 
-	The second possibility is to use “/departures” with parameter “data_freshness=base_schedule” in order to have the 10 next departures. Because you set base_schedule in your query, you can use the link “next” to have the next 10 ones ( from 11 to 20) and so on. 
-	The third option is to use the “/stop_schedule” method which will allow you to have the next X departures sort by route on the stop_area for the next 24 hours. 

Just to let you know, support for navitia.io is mostly done on https://groups.google.com/forum/#!forum/navitia . 

Hope this helps. 

Arthur

**Comment by ArthurLeyv** [comment]
Hi @tufftuff93 , 

I close this issue, feel free to reopen it or ask for more details !

Arthur
