### ISSUE TITLE
Performance issue at SpeedDistanceCombiner

### ISSUE THREAD

**Issue by skinkie** [hove-io/navitia#302]
https://github.com/CanalTP/navitia/blob/dev/source/georef/street_network.h#L41

The work done in SpeedDistanceCombiner is significant, and 10% of the total computation time of the kraken program.

**Comment by antoine-de** [comment]
I don't think this is relevant any more, I don't get those in our benchmarks since the time_duration is only a wrapper around an integer (32 now thanks to #309).
I think the performance issues were due to your compiling in debug since the boost::time_duration needs full compiler optimization to have no overhead compared to integer
