### ISSUE TITLE
Missing data in NTFS files ?

### ISSUE THREAD

**Issue by bgamassa** [hove-io/navitia#3337]
Hello Navitia team,

I have a question about the "geometries.txt" files in the NTFS dataset for "Île-de-France" zone.
Somehow, I wasn't able to find the subway and tram lines' coordinates in the file. I couldn't find them in the "trips.txt" and "routes.txt" files either. Is it because you couldn't add them or is it just a bug? :)

Thank you in advance for you reply,
Regards.

**Comment by nonifier** [comment]
Hi Binta,

Thanks for reporting this. This is a fair point and I'm not sure why this is missing. 
This could be due to some private data/process that forbids us from publishing that data. It could also mean that we don't have that data at all.

When it comes to question about data, you might have better answers from the google group as this repo is mainly software oriented:
 
https://groups.google.com/g/navitia

Hope this helps.
